[workspace]
authors = ["Jared Lumpe <jared@jaredlumpe.com>"]
channels = ["conda-forge", "bioconda"]
name = "snakemake-logger-plugin-json"
platforms = ["linux-64"]
version = "0.1.0"


# ---------------------------------------------------------------------------- #
#                                 Dependencies                                 #
# ---------------------------------------------------------------------------- #

[environments]
default = { features = ["py311", "test"]}
py312 = { features = ["py312", "test"]}
py313 = { features = ["py313", "test"]}
py314 = { features = ["py314", "test"]}


# ---------------------------------- Common ---------------------------------- #

[dependencies]

[pypi-dependencies]
snakemake-logger-plugin-json = { path = ".", editable = true }

# --------------------------------- Features --------------------------------- #

[feature.py311.dependencies]
python = "3.11.*"
[feature.py312.dependencies]
python = "3.12.*"
[feature.py313.dependencies]
python = "3.13.*"
[feature.py314.dependencies]
python = "3.14.*"

[feature.test.dependencies]
pytest = "*"


# ---------------------------------------------------------------------------- #
#                                     Tasks                                    #
# ---------------------------------------------------------------------------- #

[feature.test.tasks]
test = "pytest"
